<script setup>
import { ref, onMounted } from 'vue'
import PageHeader from '../../components/student/PageHeader.vue'
import StatusBadge from '../../components/student/StatusBadge.vue'
import { studentApi } from '../../services/studentApi'
const data=ref({upcoming:[],completed:[]}); const loading=ref(true); const error=ref('')
onMounted(async()=>{try{const r=await studentApi.getSessions();data.value=r.data||data.value}catch(e){error.value=e.message}finally{loading.value=false}})
</script>
<template><div><PageHeader title="My Sessions" subtitle="Your real booked tuition sessions."/><p v-if="loading" class="text-slate-500">Loading sessions...</p><p v-else-if="error" class="text-red-500">{{error}}</p><template v-else><section class="mb-8"><h3 class="font-display font-bold mb-3">Upcoming Sessions</h3><div v-if="!data.upcoming.length" class="card p-6 text-slate-500">No upcoming sessions booked.</div><div v-else class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-4"><div v-for="s in data.upcoming" :key="s.id" class="card card-hover p-5"><div class="flex justify-between mb-3"><h4 class="font-display font-bold">{{s.subject}}</h4><StatusBadge :status="s.status"/></div><div class="space-y-2 text-sm text-ink-soft dark:text-slate-300"><p>{{s.tutor}}</p><p>{{s.type}}</p><p>{{s.date}} · {{s.time}}</p><p>{{s.duration}}</p><a v-if="s.meeting_url || s.meetingUrl" :href="s.meeting_url || s.meetingUrl" target="_blank" rel="noopener noreferrer" class="btn grad sm inline-flex items-center justify-center mt-3">Join Meeting</a></div></div></div></section><section><h3 class="font-display font-bold mb-3">Completed Sessions</h3><div v-if="!data.completed.length" class="card p-6 text-slate-500">No completed sessions yet.</div><div v-else class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-4"><div v-for="s in data.completed" :key="s.id" class="card p-5"><div class="flex justify-between mb-3"><h4 class="font-display font-bold">{{s.subject}}</h4><StatusBadge :status="s.status"/></div><div class="space-y-2 text-sm text-ink-soft dark:text-slate-300"><p>{{s.tutor}}</p><p>{{s.date}} · {{s.time}}</p><p v-if="s.topics.length">Topics: {{s.topics.join(', ')}}</p><p v-if="s.homework">Homework: {{s.homework}}</p></div></div></div></section></template></div></template>
