<script setup>
import {ref,computed,onMounted} from 'vue';import PageHeader from '../../components/student/PageHeader.vue';import {studentApi} from '../../services/studentApi'
const tab=ref('regular'),slots=ref({regular:[],oneToOne:[]}),loading=ref(true),error=ref(''),busy=ref(null)
const active=computed(()=>slots.value[tab.value]||[])
async function load(){loading.value=true;try{const r=await studentApi.getBookingSlots();slots.value=r.data?.bookingSlots||slots.value}catch(e){error.value=e.message}finally{loading.value=false}}
async function book(s){busy.value=s.id;try{await studentApi.bookSession(s.id);await load()}catch(e){alert(e.message)}finally{busy.value=null}}
onMounted(load)
</script>
<template><div><PageHeader title="Session Booking" subtitle="Book a real session from your tutor's schedule."/><div class="inline-flex p-1 rounded-xl bg-slate-100 dark:bg-white/5 mb-6"><button class="px-5 py-2 rounded-lg text-sm font-semibold" :class="tab==='regular'?'bg-teal-100 text-teal-700':'text-slate-500'" @click="tab='regular'">Regular Sessions</button><button class="px-5 py-2 rounded-lg text-sm font-semibold" :class="tab==='oneToOne'?'bg-teal-100 text-teal-700':'text-slate-500'" @click="tab='oneToOne'">One-to-One</button></div><p v-if="loading">Loading available sessions...</p><p v-else-if="error" class="text-red-500">{{error}}</p><div v-else-if="!active.length" class="card p-8 text-center text-slate-500">No sessions are currently available. Your tutor can add one from the Tutor Schedule.</div><div v-else class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-4"><div v-for="s in active" :key="s.id" class="card p-5"><div class="flex justify-between mb-3"><h4 class="font-display font-bold">{{s.subject}}</h4><span class="text-xs font-semibold px-2.5 py-1 rounded-full" :class="s.booked?'bg-blue-100 text-blue-700':'bg-green-100 text-green-700'">{{s.booked?'Booked':'Available'}}</span></div><div class="space-y-2 text-sm text-slate-500 mb-4"><p>{{s.tutor}}</p><p>{{s.date}} · {{s.time}}</p><p>{{s.type}}</p></div><button v-if="!s.booked" class="btn grad sm" :disabled="busy===s.id" @click="book(s)">{{busy===s.id?'Booking...':'Book Session'}}</button></div></div></div></template>
